/**
 * Advisories Routes
 * GET /api/advisories — list active advisories (public)
 *
 * Advisories are now auto-generated by the system when a report's RRS
 * crosses the 0.80 threshold (see reportsRepository.updateVoteCounts).
 * No manual creation endpoint — no admin role exists.
 */

import { Router, Request, Response } from 'express';
import * as advisoriesRepository from '../repositories/advisoriesRepository';

const router = Router();

// ── GET /api/advisories ─────────────────────────────────────────────

router.get('/', async (_req: Request, res: Response): Promise<void> => {
  try {
    const advisories = await advisoriesRepository.getActive();
    res.json({ success: true, advisories });
  } catch (error) {
    console.error('List advisories error:', error);
    res.status(500).json({ success: false, error: 'Internal server error.' });
  }
});

export default router;
